### ISSUE TITLE
Shortcut's reset button closes the alert without saving the change.

### ISSUE THREAD

**Issue by raszpl** [code-for-charity/satus#7]

**Comment by raszpl** [comment]
same bug when clicking Cancel

https://github.com/code-charity/youtube/blob/417ae81c536bb0a04751157bb7002f15cd75d3a9/js%26css/satus.js#L2337

satus.storage.remove/satus.storage.get expect key, not whole .storage element, trivial fix incoming

**Comment by ImprovedTube** [comment]
> same 

same?🤔 (cancel doesnt need to change storage like reset does)

**Comment by raszpl** [comment]
yep, cancel didnt work either satus.storage.get needs a key string, but what was being passed was key/value pair.
